name: social_media_toolkit
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  pdf: ^3.11.2
  printing: ^5.14.0
  path_provider: ^2.1.5
  file_picker: ^8.3.1
  image_picker: ^1.1.2
  flutter_dropzone: ^4.2.1
  dotted_border: ^2.1.0
  go_router: ^14.7.2
  dynamic_path_url_strategy: ^1.0.0
  image: ^4.5.2
  flutter_image_compress: ^2.4.0
  url_launcher: ^6.3.1
  web: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true